# Deployment da aplicação
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversor-temperatura
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: rodddmarques/conversao-temperatura:v3
        ports:
        - containerPort: 8080

---
#Service da aplicação
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer

